Repository bright/new-www, pull requests merged in 2020-12, with the labels that each got.

#221 Update Jobs “android-developer”
  src/pages/jobs/android-developer.md
Labels: netlify-cms/pending_publish

#222 Update Jobs “fullstack-developer-interest-in-blockchain”
  src/pages/jobs/fullstack-developer-interest-in-blockchain.md
Labels: netlify-cms/pending_publish

#223 Update Jobs “ios-developer”
  src/pages/jobs/ios-developer.md
Labels: netlify-cms/pending_publish

#224 Update Jobs “backend-developer”
  src/pages/jobs/backend-developer.md
Labels: netlify-cms/pending_publish

#225 Create Jobs “frontend-developer”
  src/pages/jobs/frontend-developer.md
Labels: netlify-cms/pending_publish

#226 Create Jobs “senior-automation-developer-mobile-web”
  src/pages/jobs/senior-automation-developer-mobile-web.md
Labels: netlify-cms/pending_publish

#232 Create Members “łukasz-reszetow”
  src/pages/about-us/łukasz-reszetow.md
Labels: netlify-cms/draft

#234 [wojciech] bio & blogpost
  package-lock.json
  src/pages/about-us/team/wojciech-baczynski.md
  src/pages/blog/2020-12-28-covariance-contravariance.md
  static/images/covariance-contravariance/graph-1.png
  static/images/covariance-contravariance/graph-2.png
  static/images/covariance-contravariance/graph-3.png
  static/images/wojciech.jpg
Labels: blog
